package ArrayGenerator;

/**
 * Defines the interface for classes that generate arrays
 * <p>
 * The constructor for implementations of this class should generate an array 
 * of objects
 * <p>
 * <i>This is an interface, and specifies the signature(s) of method(s) that
 * you should implement in (a) <b>separate</b> class(es).  You should <b>not</b> edit
 * this class! 
 * 
 * @author Hugh Osborne
 * @version October 2013
 */

public interface ArrayGenerator
{
    /**
     * @return the array of ints generated by this ArrayGenerator
     */
    public int[] array();
}
